version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: echo "Hello, shruti!"
    steps:
      - checkout
      - run:
         name: Run Python Script
         command: python app.py  # Replace with your script name

